### ISSUE TITLE
Ack does not work

### ISSUE THREAD

**Issue by eelcocramer** [nats-io/asyncio-nats-streaming#5] opened 2017-12-07 12:36 UTC
Hey there,

We are currently working on a streaming python client that reads from NATS streaming, does some processing and then publishes the result into another subject in NATS streaming. See the code below:

```python
    # ---8< code was cut here >8---

    async def cb(msg):
        nonlocal sc
        
        # when I ack the message directly the code works fine
        # await sc.ack(msg)

        # doing some processing here to create pubmsg
        pubmsg = ...

        await sc.publish('processed', pubmsg)
        # this ack does not keep NATS streaming from resending the message after 30s
        await sc.ack(msg)

    await sc.subscribe('notprocessed', start_at='first', cb=cb, manual_acks=True, ack_wait=30)

    # ---8< code was cut here >8---
```

The processing takes way shorter than the 30 seconds timeout for re-sends. Pulling the ack up in the code makes this sample work like expected.

Any ideas of what we do wrong?

**Comment by eelcocramer** [comment] 2017-12-07 13:44
Please note that I've also tried calling the `ack` from within a callback of the `publish` call, which is probably preferable as we only want to ack when the new message was published successfully, but we got the same results.

**Comment by DavidBord** [comment] 2019-04-01 21:59
This happened to me as well. @wallyqs I would happily provide any additional information needed here

**Comment by juandiegopalomino** [comment] 2019-04-02 17:34
@wallyqs maybe this is the same issue as https://github.com/nats-io/nats-streaming-server/issues/780?

**Comment by wallyqs** [comment] 2019-04-03 18:09
Thanks @juandiegopalomino @DavidBord for pinging on this issue.

I took another look and ack functionality itself is working, so I think in this case either one of the two couple of things could be happening in this working:

1) Message processing within the subscribe callback is taking longer than ack wait so the message gets redelivered
2) There was an exception within the subscribe callback which is using manual acks, so the message continuously gets redelivered.

Could it be possible that maybe running into one of those conditions? For 2) using `try/except` within the callback could help debug the issue as well.

```python
    async def cb(msg):
        try:
            print("Received a message on sub 'foo' (seq: {}): {}".format(msg.sequence, msg.data))

            await sc.publish("bar", b'done!')
            await sc.ack(msg)
        except Exception as e:
            print("ERROR: ", e)
    await sc.subscribe("foo", start_at='first', cb=cb, manual_acks=True, ack_wait=1)
```

Also in the latest release it was added an `error_cb` field to be able to inspect errors during the processing of the callback, an example with usage is below:

```
import asyncio
from nats.aio.client import Client as NATS
from stan.aio.client import Client as STAN

async def run(loop):
    nc = NATS()
    sc = STAN()
    await nc.connect(io_loop=loop)
    await sc.connect("test-cluster", "client-123", nats=nc)

    for i in range(0, 10):
        await sc.publish("foo", b'hello-world',
                         ack_handler=lambda ack: print("Received ack: {}".format(ack.guid)))

    for i in range(0, 10):
        ack = await sc.publish("foo", b'hello-world')
        print("Received ack: ", ack.guid)

    async def error_cb(err):
        print("ERROR:", err)

    # Manual ack version
    async def cb(msg):
        print("Received a message on sub 'foo' (seq: {}): {}".format(msg.sequence, msg.data))

        await sc.publish("bar", b'done!')
        await sc.ack(msg)
    await sc.subscribe("foo", start_at='first', cb=cb, manual_acks=True, ack_wait=1, error_cb=error_cb)
    
    # Automatic acks version
    async def cb2(msg):
        print("Received a message on sub 'bar' (seq: {}): {}".format(msg.sequence, msg.data))
    await sc.subscribe("bar", start_at='first', cb=cb2, error_cb=error_cb)

    for i in range(0, 120):
        await asyncio.sleep(1, loop=loop)
    await sc.close()
    await nc.close()

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run(loop))
    loop.close()
```

**Comment by juandiegopalomino** [comment] 2019-04-03 21:39
@wallyqs thank you for taking a further look at this
two address your cases:
For the exception in the callback, I think we can rule that out as we have as close to bulletproof error handling as we could manage-- we've setup an array of logs, try-catches, and error-guarding contexts that I have not seen fail, nor output incoherent logs in ages.

For the timeout case: it could be that every now and then we go over the timeout, but we're seeing old messages redelivered in unexpected numbers. Furthermore, we added a cache based on the sequence id (the subscriber is for a sole channel and the only consumer) to quickly identify duplicate deliveries that have been handled successfully and immediately acknowledge them as they should have never been seen again to begin with. Unfortunately even though we acknowledge within about a millisecond, the message is redelivered again after a minute and a half or so (the wait timeout is 1 minute). You may find some of my logs here:

```
2019-04-03 21:11:19,924 Job=aa23eb7b-63ed-411c-b474-e4bd0c149909 Env=dev Level=INFO PID=1 Thread=MainThread event_poller.py:63   Received msg <nats streaming msg sequence=2050, time=1554323792650834340> w/ data b'{"data": {"type": "event-message", "attributes": {"publisher": "streamy_admin", "workflow_instance_id": "aa23eb7b-63ed-411c-b474-e4bd0c149909", "vertex_job_id": "49ec463e-4b69-4e25-bb65-cb11f819b912", "message": {"successor_input": {"flow_inputs": []}, "event_ts": "2019-04-03 20:36:32.601871+00:00"}, "event_type": "JobOutput"}, "meta": {"service": "event"}}}'
2019-04-03 21:11:19,925 Job=aa23eb7b-63ed-411c-b474-e4bd0c149909 Env=dev Level=WARNING PID=1 Thread=MainThread event_poller.py:67   We already succesfully handled message with sequence id 2050 before, so not doing anything this time
2019-04-03 21:11:19,925 Job=aa23eb7b-63ed-411c-b474-e4bd0c149909 Env=dev Level=INFO PID=1 Thread=MainThread timers.py:42   TimerName=nats_streaming.ack [TIMER 0.000 seconds]
2019-04-03 21:11:19,925 Job=aa23eb7b-63ed-411c-b474-e4bd0c149909 Env=dev Level=INFO PID=1 Thread=MainThread timers.py:42   TimerName=_handle_nats_message [TIMER 0.001 seconds]
.
.
.
2019-04-03 21:12:42,102 Job=aa23eb7b-63ed-411c-b474-e4bd0c149909 Env=dev Level=INFO PID=1 Thread=MainThread event_poller.py:63   Received msg <nats streaming msg sequence=2050, time=1554323792650834340> w/ data b'{"data": {"type": "event-message", "attributes": {"publisher": "streamy_admin", "workflow_instance_id": "aa23eb7b-63ed-411c-b474-e4bd0c149909", "vertex_job_id": "49ec463e-4b69-4e25-bb65-cb11f819b912", "message": {"successor_input": {"flow_inputs": []}, "event_ts": "2019-04-03 20:36:32.601871+00:00"}, "event_type": "JobOutput"}, "meta": {"service": "event"}}}'
2019-04-03 21:12:42,103 Job=aa23eb7b-63ed-411c-b474-e4bd0c149909 Env=dev Level=WARNING PID=1 Thread=MainThread event_poller.py:67   We already succesfully handled message with sequence id 2050 before, so not doing anything this time
2019-04-03 21:12:42,103 Job=aa23eb7b-63ed-411c-b474-e4bd0c149909 Env=dev Level=INFO PID=1 Thread=MainThread timers.py:42   TimerName=nats_streaming.ack [TIMER 0.000 seconds]
2019-04-03 21:12:42,103 Job=aa23eb7b-63ed-411c-b474-e4bd0c149909 Env=dev Level=INFO PID=1 Thread=MainThread timers.py:42   TimerName=_handle_nats_message [TIMER 0.001 seconds]
```

This is what the beginning of the handler looks like:
```
    async def _handle_nats_message(self, msg):
        with Timer(logger, timer_name="_handle_nats_message", log_level="info"):
            with ExceptionLogger(logger, "Event poller got the following error"):
                logger.info("Received msg {} w/ data {}".format(msg, msg.data))
                if msg.seq in self.seen_seq_ids:
                    logger.warn(
                        ("We already succesfully handled message with sequence id {} before, so not doing anything"
                         " this time").format(msg.seq))
                    with Timer(logger, timer_name="nats_streaming.ack", log_level="info"):
                        await self.nats_streaming.ack(msg)
                    return
```

This redelivery happens randomly and no more than single-digit percentages of the time (for this instance I also don't see any redeliveries prior to message 2K). I have no idea what I'm missing (maybe something w/ the nats streaming server?), and if you have any ideas I'd really appreciate them.

**Comment by wallyqs** [comment] 2019-04-04 08:48
Thinking what might be going on to reproduce... 🤔 maybe what is happening is that the ack wait was 1 minute, so redelivery gets scheduled to occur every minute until the consumer acks the message. Since the library only handles a message at a time sequentially / in order, if a message being processed takes let's say 5 minutes, then this will cause the message to be delivered 5 times.  The messages will be internally buffered by the client library as many times as the server sends them, so even though the messages have already been acked successfully and skipped by the "seen" logic  it will look like as if the messages are still being sent by the server but actually they are the messages being buffered in the client side. If this happens several times, then the accumulation of the redeliveries may look as if the acked messages are still being sent by the server.

```python
import asyncio
from nats.aio.client import Client as NATS
from stan.aio.client import Client as STAN

async def run(loop):
    nc = NATS()
    sc = STAN()
    await nc.connect(io_loop=loop)
    await sc.connect("test-cluster", "client-123", nats=nc)

    for i in range(0, 4096):
        await sc.publish("foo", b'hello-world',
                         ack_handler=lambda ack: print("Received ack: {}".format(ack.guid)))

    seen = []

    # Manual ack version
    async def cb(msg):
        if msg.sequence in seen:
            print("Skipped message on sub 'foo' (seq: {}): {}".format(msg.sequence, msg.data))
            await sc.ack(msg)
            return
        print("Received a message on sub 'foo' (seq: {}): {}".format(msg.sequence, msg.data))
        try:
            # Process
            await asyncio.sleep(0.01)
            await sc.ack(msg)
            seen.append(msg.sequence)
        except Exception as e:
            print("ERROR: ", e)
    await sc.subscribe("foo", start_at='first', cb=cb, manual_acks=True, ack_wait=1)
    
    for i in range(0, 120):
        await asyncio.sleep(1, loop=loop)
    await sc.close()
    await nc.close()

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run(loop))
    loop.close()
```

**Comment by juandiegopalomino** [comment] 2019-04-04 16:08
@wallyqs interesting point (and one which might need to be guarded against), but unfortunately it does not explain the lag between the redeliveries. If we are receiving the n redeliveries after taking n minutes more (which definitely is not the case-- only the most extreme cases took over 1 minute and never over 2, and definitely not x >> 1 as we're getting redeliveries x times), then they would be in the client's buffer and so should be bunched together, not re-appear every minute or so (and when they do, they appear in a big chunk of messages to redeliver).
But now that I think about it, while the messages each take < 1 minute, we do get a lot of them in quick succession and the client buffer could be somewhat large. If the ack timeout is against the times since the message got _in the buffer_, rather than the time spent in the message handler, then I suppose that might explain it.

**Comment by wallyqs** [comment] 2019-04-05 06:55
@juandiegopalomino yes I think that is what might be happening, the client could be buffering several redeliveries.  First will add the following to be able to confirm the status of the client buffer: https://github.com/nats-io/asyncio-nats-streaming/compare/pending-queue-size
Also need to consider whether need to add some logic to the client to ignore buffered messages that have already been acked...

**Comment by DavidBord** [comment] 2019-04-05 11:29
@wallyqs I think that what happened to me is a bit different:
- I run a producer producing 10 random messages.
- Run 2 consumers that consumed from the same durable queue.
- Stopped one of the consumers before ack on one of the messages
- The other consumer consumed the rest of the messages
- A bit later this consumer consumed the message from the first producer
- A bit later this consumer consumed all the 10 messages

It wasn't a one-off. This happened to me at least 5 times.

I tried to re-run this scenario with your suggestions but unfortunately the issue didn't reproduce.

**Comment by wallyqs** [comment] 2019-04-05 11:54
Thanks @DavidBord that sounds like a different issue then, can you share more info about how you are starting the subscription & ack timeout? Also in case available streaming server logs with -SDV could help...

**Comment by juandiegopalomino** [comment] 2019-04-05 16:58
@wallyqs awesome, it looks like we where right-- we dropped the max inflight from the default down to 10 and we haven't gotten the issue since. Funnily enough we also did an update yesterday to log msg.sub._msgs_queue.qsize() directly (but using a property is more correct). Thank you for all your help!

**Comment by wallyqs** [comment] 2019-04-05 17:39
Thanks for the update @juandiegopalomino, that is great news 👍

**Comment by wallyqs** [comment] 2019-04-08 05:48
Closing this one since think we covered many scenarios where it may look as if ack is not working, @DavidBord let me know if you manage to reproduce and can reopen or maybe create a new one to address that case in separate. Thanks everyone for the feedback related to this issue.

**Closed by wallyqs** 2019-04-08 05:48 UTC

**Comment by AkshayAnjAmerica** [comment] 2024-01-22 06:49
i have facing similar issue in my project. @wallyqs  I have tried solution you mensioned above using a array of seen to ack(). but there is a issue again , in my project  its a microservice project and when i restarted my python pod , all the previous events from nats get executes again . how to solve this.
